### PR TITLE
add dinner

### PR DESCRIPTION
**Pull request by raynamharris**
dinner option cc @davissn30

### CODE REVIEW

**Comment by davissn30** [comment]
We have arranged for a group dinner on the first night of the meeting (Wednesday, July 25) at [Kipos](http://kiposchapelhill.com/), 431 W. Franklin Street, Chapel Hill, North Carolina 27514. There will be a bus (and passenger van and carpools) that will take everyone down to Franklin Street right after the meeting ends on Wednesday. After dinner is over, you can take the bus back to the Sheraton, or you can stay on Franklin Street to sample the many evening activities and Uber home.

**Comment by raynamharris** [comment]
Thanks @davissn30 I'll update that now.

**Comment by davissn30** [comment]
@raynamharris  a few issues with the group dinner information on the July workshop website. 1) The days are wrong. It's Tuesday the 24th and Wednesday the 25th. 2) Can you add the time for the dinner at Namu (7pm).

**Comment by raynamharris** [comment]
Thanks @davissn30. I'm not sure what I was thinking with Th/F. These are fixed now with cab8aab97799da12a8325f24abd70e0e6dfbefc9

**Comment by davissn30** [comment]
This is why we have many eyes.

**Pull request merged**
